### ISSUE TITLE
Is there a way to also highlight 8-digit hex colors?

### ISSUE THREAD

**Issue by PLRrex** [heatherpiper/color-highlighter#1]
Hi. Thank you for this great plugin.

I was wondering if it would be possible to also highlight 8-digit hex colors (and perhaps its shorthand form, the 4-digit hex colors)?

Thank you in advance.

**Comment by heatherpiper** [comment]
Thank you for your suggestion! I've just added support for 8-digit and 4-digit hex formats. They should work in the next release :)
